apps/fandom/urls.py
from django.conf.urls import url
from .views import *

app_name = 'fandom'

urlpatterns = [
    # 圈子列表页
    url(r'^list/', QaunListView.as_view(),name="fandom_list"),
    # 圈子详情页
    url(r'^home/(?P<fandom_id>\d+)/$', fandomHomeView.as_view(),name="fandom_home"),
    # 圈子视频
    url(r'^fandom_video/(?P<fandom_id>\d+)/$', FanVideoView.as_view(), name="fandom_video"),
    # 圈子图片
    url(r'^fandom_picture/(?P<fandom_id>\d+)/$', FanPictureView.as_view(), name="fandom_picture"),
    # 圈子帖子
    url(r'^fandom_article/(?P<fandom_id>\d+)/$', FanArticleView.as_view(), name="fandom_article"),
    # 圈子活动
    url(r'^fandom_activity/(?P<fandom_id>\d+)/$', FanActivityView.as_view(), name="fandom_activity"),

    # 帖子列表页
    url(r'^article/list/', ArticleView.as_view(), name="article_list"),
    # 帖子详情页
    url(r'^article/detail/(?P<article_id>\d+)/$', articleDetailView.as_view(), name="article_detail"),

    # 视频列表页
    url(r'^video/list/', VideoView.as_view(), name="video_list"),
    # 视频详情页
    url(r'^video/detail/(?P<video_id>\d+)/$', VideoDetailView.as_view(), name="video_detail"),

    # 图片列表页
    url(r'^picture/list/', PictureView.as_view(), name="picture_list"),
    # 图片详情页
    url(r'^picture/detail/(?P<picture_id>\d+)/$', PictureDetailView.as_view(), name="picture_detail"),

    # 活动列表页
    url(r'^activity/list/', ActivityView.as_view(), name="activity_list"),
    # 活动详情页
    url(r'^activity/detail/(?P<activity_id>\d+)/$', ActivityDetailView.as_view(), name="activity_detail"),

    # 添加收藏
    url(r'^add_fav/$', AddFavView.as_view(), name="add_fav"),

]

apps/users/urls.py
from django.conf.urls import url,include
from .views import *

app_name = 'users'
urlpatterns = [
    # 用户信息页
    url(r'^info/', UserInfoView.as_view(),name="user_info"),
    # 用户上传头像
    url(r'^image/upload/$', UpLoadImageView.as_view(),name="image_upload"),
    # 个人中心修改密码
    url(r'^update/pwd/$', UpdatePwdView.as_view(),name="update_pwd"),
    # 发送邮箱验证码
    url(r'^sendemail_code/$', SendEmailCodeView.as_view(), name="sendemail_code"),
    # 修改邮箱
    url(r'^update_email/$', UpdataEmailView.as_view(), name="update_email"),

    # 我的圈子
    url(r'^myfav/fandom/$', MyFavFanView.as_view(), name="myfav_fandom"),

    # 我收藏的视频
    url(r'^myfav/video/$', MyFavVidView.as_view(), name= "myfav_video"),
    # 我收藏的图片
    url(r'^myfav/picture/$', MyFavPicView.as_view(), name= "myfav_picture"),
    # 我收藏的帖子
    url(r'^myfav/article/$', MyFavArtView.as_view(), name= "myfav_article"),

    # 我发表的视频
    url(r'^mypo/video/$', MyPoVidView.as_view(), name="mypo_video"),
    # 我发表的图片
    url(r'^mypo/picture/$', MyPoPicView.as_view(), name="mypo_picture"),
    # 我发表的帖子
    url(r'^mypo/article/$', MyPoArtView.as_view(), name="mypo_article"),
    # 我发表的评论
    url(r'^mypo/comment/$', MyPoComView.as_view(), name="mypo_comment"),
    #删除发表
    url(r'^del_po/$', DelPoView.as_view(), name="del_po"),


    #上传帖子
    url(r'^new/article/(?P<fandom_id>\d+)/$', newArticleView.as_view(), name="new_article"),
    #上传视频
    url(r'^new/video/(?P<fandom_id>\d+)/$', newVideoView.as_view(), name="new_video"),
    # 上传图片
    url(r'^new/picture/(?P<fandom_id>\d+)/$', newPictureView.as_view(), name="new_picture"),

    # 发表评论
    url(r'^new/comment/(?P<article_id>\d+)/$', newCommentView.as_view(), name="new_comment"),

    # 回复评论
    url(r'^reply/comment/(?P<comment_id>\d+)/$', replyCommentView.as_view(), name="reply"),

    url(r'^p1',p1View.as_view(), name="p1"),
    url(r'^p2',p2View.as_view(), name="p2"),

]

myFandom/urls.py
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib import staticfiles
from django.conf.urls import url,include
from django.contrib import admin
from django.views.static import serve
from django.views.generic import TemplateView
import xadmin
from users.views import IndexView

from users.views import *
from users import views

from myFandom.settings import MEDIA_ROOT

urlpatterns = [
    url(r'^login/$', LoginView.as_view(),
        name="login"),  # 登录

    url(r'^$', IndexView.as_view(),name="index"),#首页
    url(r'^xadmin/', xadmin.site.urls),#管理后台
    url(r'^logout/$', LogOutView.as_view(),name="logout"),#登出
    url(r'^register/$',  RegisterView.as_view(),name="register"),#注册
    url(r'^captcha/', include('captcha.urls')),#验证码

    #通过(?P.*？)正则获取获取匹配的字符串（实际就是发送的验证码），
    # 绑定ActiveUserView，通过该类完成激活
    url(r'^active/(?P<active_code>.*?)/$', ActiveUserView.as_view(), name="ActiveUserView"),
    url(r'^forget/$', ForgetPwdView.as_view(),name="ForgetPwdView"),#忘记密码
    url(r'^reset/(?P<active_code>.*?)/$', ResetView.as_view(),name="ResetView"),#重置密码
    url(r'^modify_pwd/$', ModifyPwdView.as_view(),name="ModifyPwdView"),#更改密码

    # 圈子相关URL配置
    url(r'^fandom/', include('fandom.urls')),
    # 用户相关URL配置
    url(r'^users/', include('users.urls')),
    # 用户操作相关URL配置
    url(r'^operation/', include('operation.urls')),
    # 配置上传文件访问处理函数
    url(r'^media/(?P<path>.*)$', serve,{"document_root":MEDIA_ROOT}),
    # 富文本相关URL
    url(r'^ueditor/',include('DjangoUeditor.urls' )),
    # url(r'^static/(?P<path>.*)$', serve,{"document_root":STATIC_ROOT}),
]
#全局404 500 页面配置
# (放ViewS的路径)
handler404='users.views.page_not_found'
handler500='users.views.page_error'

urlpatterns += staticfiles_urlpatterns()

extra_apps/xadmin/views/base.py
import copy
import functools
import datetime
import decimal
from functools import update_wrapper
from inspect import getfullargspec

from django import forms
from django.apps import apps
from django.conf import settings
from django.contrib import messages
from django.contrib.auth import get_permission_codename
from django.core.exceptions import ValidationError
from django.core.serializers.json import DjangoJSONEncoder
from django.urls.base import reverse
from django.http import HttpResponse
from django.template import Context, Template
from django.template.response import TemplateResponse
from django.utils import six
from django.utils.decorators import method_decorator, classonlymethod
from django.utils.encoding import force_text, smart_text, smart_str
from django.utils.functional import Promise
from django.utils.http import urlencode
from django.utils.itercompat import is_iterable
from django.utils.safestring import mark_safe
from django.utils.text import capfirst
from django.utils.translation import ugettext as _
from django.views.decorators.csrf import csrf_protect
from django.views.generic import View
from collections import OrderedDict
from xadmin.util import static, json, vendor, sortkeypicker

from xadmin.models import Log

csrf_protect_m = method_decorator(csrf_protect)


class IncorrectPluginArg(Exception):
    pass


def get_content_type_for_model(obj):
    from django.contrib.contenttypes.models import ContentType
    return ContentType.objects.get_for_model(obj, for_concrete_model=False)


def filter_chain(filters, token, func, *args, **kwargs):
    if token == -1:
        return func()
    else:
        def _inner_method():
            fm = filters[token]
            fargs = getfullargspec(fm)[0]
            if len(fargs) == 1:
                # Only self arg
                result = func()
                if result is None:
                    return fm()
                else:
                    raise IncorrectPluginArg(u'Plugin filter method need a arg to receive parent method result.')
            else:
                return fm(func if fargs[1] == '__' else func(), *args, **kwargs)
        return filter_chain(filters, token - 1, _inner_method, *args, **kwargs)


def filter_hook(func):
    tag = func.__name__
    func.__doc__ = "``filter_hook``\n\n" + (func.__doc__ or "")

    @functools.wraps(func)
    def method(self, *args, **kwargs):

        def _inner_method():
            return func(self, *args, **kwargs)

        if self.plugins:
            filters = [(getattr(getattr(p, tag), 'priority', 10), getattr(p, tag))
                       for p in self.plugins if callable(getattr(p, tag, None))]
            filters = [f for p, f in sorted(filters, key=lambda x:x[0])]
            return filter_chain(filters, len(filters) - 1, _inner_method, *args, **kwargs)
        else:
            return _inner_method()
    return method


def inclusion_tag(file_name, context_class=Context, takes_context=False):
    def wrap(func):
        @functools.wraps(func)
        def method(self, context, nodes, *arg, **kwargs):
            _dict = func(self, context, nodes, *arg, **kwargs)
            from django.template.loader import get_template, select_template
            cls_str = str if six.PY3 else basestring
            if isinstance(file_name, Template):
                t = file_name
            elif not isinstance(file_name, cls_str) and is_iterable(file_name):
                t = select_template(file_name)
            else:
                t = get_template(file_name)

            _dict['autoescape'] = context.autoescape
            _dict['use_l10n'] = context.use_l10n
            _dict['use_tz'] = context.use_tz
            _dict['admin_view'] = context['admin_view']

            csrf_token = context.get('csrf_token', None)
            if csrf_token is not None:
                _dict['csrf_token'] = csrf_token
            nodes.append(t.render(_dict))

        return method
    return wrap


class JSONEncoder(DjangoJSONEncoder):

    def default(self, o):
        if isinstance(o, datetime.datetime):
            return o.strftime('%Y-%m-%d %H:%M:%S')
        elif isinstance(o, datetime.date):
            return o.strftime('%Y-%m-%d')
        elif isinstance(o, decimal.Decimal):
            return str(o)
        elif isinstance(o, Promise):
            return force_text(o)
        else:
            try:
                return super(JSONEncoder, self).default(o)
            except Exception:
                return smart_text(o)


class BaseAdminObject(object):

    def get_view(self, view_class, option_class=None, *args, **kwargs):
        opts = kwargs.pop('opts', {})
        return self.admin_site.get_view_class(view_class, option_class, **opts)(self.request, *args, **kwargs)

    def get_model_view(self, view_class, model, *args, **kwargs):
        return self.get_view(view_class, self.admin_site._registry.get(model), *args, **kwargs)

    def get_admin_url(self, name, *args, **kwargs):
        return reverse('%s:%s' % (self.admin_site.app_name, name), args=args, kwargs=kwargs)

    def get_model_url(self, model, name, *args, **kwargs):
        return reverse(
            '%s:%s_%s_%s' % (self.admin_site.app_name, model._meta.app_label,
                             model._meta.model_name, name),
            args=args, kwargs=kwargs, current_app=self.admin_site.name)

    def get_model_perm(self, model, name):
        return '%s.%s_%s' % (model._meta.app_label, name, model._meta.model_name)

    def has_model_perm(self, model, name, user=None):
        user = user or self.user
        return user.has_perm(self.get_model_perm(model, name)) or (name == 'view' and self.has_model_perm(model, 'change', user))

    def get_query_string(self, new_params=None, remove=None):
        if new_params is None:
            new_params = {}
        if remove is None:
            remove = []
        p = dict(self.request.GET.items()).copy()
        arr_keys = list(p.keys())
        for r in remove:
            for k in arr_keys:
                if k.startswith(r):
                    del p[k]
        for k, v in new_params.items():
            if v is None:
                if k in p:
                    del p[k]
            else:
                p[k] = v
        return '?%s' % urlencode(p)

    def get_form_params(self, new_params=None, remove=None):
        if new_params is None:
            new_params = {}
        if remove is None:
            remove = []
        p = dict(self.request.GET.items()).copy()
        arr_keys = list(p.keys())
        for r in remove:
            for k in arr_keys:
                if k.startswith(r):
                    del p[k]
        for k, v in new_params.items():
            if v is None:
                if k in p:
                    del p[k]
            else:
                p[k] = v
        return mark_safe(''.join(
            '<input type="hidden" name="%s" value="%s"/>' % (k, v) for k, v in p.items() if v))

    def render_response(self, content, response_type='json'):
        if response_type == 'json':
            response = HttpResponse(content_type="application/json; charset=UTF-8")
            response.write(
                json.dumps(content, cls=JSONEncoder, ensure_ascii=False))
            return response
        return HttpResponse(content)

    def template_response(self, template, context):
        return TemplateResponse(self.request, template, context)

    def message_user(self, message, level='info'):
        """
        Send a message to the user. The default implementation
        posts a message using the django.contrib.messages backend.
        """
        if hasattr(messages, level) and callable(getattr(messages, level)):
            getattr(messages, level)(self.request, message)

    def static(self, path):
        return static(path)

    def vendor(self, *tags):
        return vendor(*tags)

    def log(self, flag, message, obj=None):
        log = Log(
            user=self.user,
            ip_addr=self.request.META['REMOTE_ADDR'],
            action_flag=flag,
            message=message
        )
        if obj:
            log.content_type = get_content_type_for_model(obj)
            log.object_id = obj.pk
            log.object_repr = force_text(obj)
        log.save()


class BaseAdminPlugin(BaseAdminObject):

    def __init__(self, admin_view):
        self.admin_view = admin_view
        self.admin_site = admin_view.admin_site

        if hasattr(admin_view, 'model'):
            self.model = admin_view.model
            self.opts = admin_view.model._meta

    def init_request(self, *args, **kwargs):
        pass


class BaseAdminView(BaseAdminObject, View):
    """ Base Admin view, support some comm attrs."""

    base_template = 'xadmin/base.html'
    need_site_permission = True

    def __init__(self, request, *args, **kwargs):
        self.request = request
        self.request_method = request.method.lower()
        self.user = request.user

        self.base_plugins = [p(self) for p in getattr(self,
                                                      "plugin_classes", [])]

        self.args = args
        self.kwargs = kwargs
        self.init_plugin(*args, **kwargs)
        self.init_request(*args, **kwargs)

    @classonlymethod
    def as_view(cls):
        def view(request, *args, **kwargs):
            self = cls(request, *args, **kwargs)

            if hasattr(self, 'get') and not hasattr(self, 'head'):
                self.head = self.get

            if self.request_method in self.http_method_names:
                handler = getattr(
                    self, self.request_method, self.http_method_not_allowed)
            else:
                handler = self.http_method_not_allowed

            return handler(request, *args, **kwargs)

        # take name and docstring from class
        update_wrapper(view, cls, updated=())
        view.need_site_permission = cls.need_site_permission

        return view

templates/fandom-detail-homepage.html
{% extends 'fandom_base.html' %}
{% block title %}粉丝圈首页{% endblock %}
{% block page_path %}{{fandom.q_name}}{% endblock %}
{% load staticfiles %}
{% block right_form %}

<div class="right companycenter layout grouping" >
		<div class="head">
			<h1>{{fandom.q_name}}</h1>
			<div class="gz_btn fr notlogin" onclick="add_fav(this,{{ fandom.id }},4)" >
                {% if has_fav %}已关注{% else %}关注{% endif %}
		    </div>
		</div>
		<div class="brief group_list">

		</div>

	<script type="text/javascript">
    //关注按钮
function add_fav(current_elem, fav_id, fav_type){
    $.ajax({
        cache: false,
        type: "POST",
        url:"{% url 'fandom:add_fav' %}",
        data:{'fav_id':fav_id, 'fav_type':fav_type},
        async: true,
        beforeSend:function(xhr, settings){
            xhr.setRequestHeader("X-CSRFToken", "{{ csrf_token }}");
        },
        success: function(data) {
            if(data.status == 'fail'){
                if(data.msg == '用户未登录'){
                    window.location.href="/login";
                }else{
                    alert(data.msg)
                }

            }else if(data.status == 'cancelSuccess'){
                //current_elem.text(data.msg)
                alert('取消关注成功')


            }
            else if(data.status == 'success'){
                //current_elem.text(data.msg)
                alert('关注成功');
            }
        },
    });
}

$('.collectionbtn2').on('click', function(){
    alert({{ picture.id }})
    //add_fav($(this), {{ fandom.id }}, 4);
});
</script>
{% endblock %}

templates/fandom_base.html
<!DOCTYPE html>
<html>
{% load staticfiles %}
<head>
	<meta charset="UTF-8">
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1" >
	<title>{% block title %}粉丝圈首页{% endblock %}</title>
	<link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/po/component.css' %}" />
	<link rel="stylesheet" type="text/css" href="{% static 'css/po/content.css' %}" />
    <link href="{% static 'bootstrap-3.3.7-dist/css/bootstrap.min.css' %}" rel="stylesheet" type="text/css" media="all" />

    <script src="{% static 'js/jquery.min.js' %}" type="text/javascript"></script>
    <script src="{% static 'js/deco-common.js' %}"  type="text/javascript"></script>
    <script src="{% static 'js/plugins/jquery.scrollLoading.js' %}"  type="text/javascript"></script>
    <script src="{% static 'bbs/js/post-detail.js' %}"  type="text/javascript"></script>
    <script src="{% static 'js/modernizr.custom.js' %}"></script>
    <script src="{% static 'js/classie.js' %}"></script>
    <script src="{% static 'js/uiMorphingButton_fixed.js' %}"></script>

</head>
<body>
<section class="headerwrap headerwrap2">
    <header>
		<div  class="header2 header">
            <div class="top">
                <div class="wp">
					<!--登录后跳转-->
						{% if request.user.is_authenticated %}
                    <div class="personal">
                            <dl class="user fr">
                                <dd>{{ user.username }}<img class="down fr" src="{% static 'images/top_down.png' %}"/></dd>
                                <dt><img width="50" height="50" src="/media/{{ request.user.image }}"/></dt>
                            </dl>
                            <div class="userdetail">
                            	<dl>
	                                <dt><img width="80" height="80" src="/media/{{ request.user.image }}"/></dt>
	                                <dd>
	                                    <h2>{{ request.user.nick_name }}</h2>
	                                    <p>{{ request.user.username }}</p>
	                                </dd>
                                </dl>
                                <div class="btn">
	                                <a class="personcenter fl" href="{% url 'users:user_info' %}">进入个人中心</a>
	                                <a class="fr" href="{% url 'logout' %}?next={{ request.path }}">退出</a>
                                </div>
                            </div>
                    </div>
                    {% else %}
                        <a style="color:white" class="fr registerbtn" href="{% url 'register' %}?next={{ request.path }}">注册</a>
                        <a style="color:white" class="fr loginbtn" href="{% url 'login' %}?next={{ request.path }}">登录</a>
                    {% endif %}
{% block login-head %}{% endblock %}
                        <div class="head fl">
                            <h1>
                                <span style="font-family: fandomFont;font-size:45px;color:#FA58F4;">饭圈:</span><span style="font-family: fandomFont;font-size:60px;color:#FA58F4;">{{ fandom.q_name}}</span>
                            </h1>
                        </div>
                </div>

			    </div>
    </header>
</section>
<section>
	<div class="wp">

        <ol class="breadcrumb" style="margin-top:10px;">
            <li><a href="{% url 'index' %}">首页</a></li>
			<li><a href="{% url 'fandom:fandom_list' %}">圈子</a></li>
			<li>{% block page_path %}{% endblock %}</li>
        </ol>
	</div>
</section>

<section>
	<div class="wp list personal_list comp">
		<div class="left">
			<ul>
				<li class="{% ifequal current_page 'home' %}active2{% endifequal %}"><a href="{% url 'fandom:fandom_home' fandom.id %}">粉丝圈首页</a></li>
                <li class="{% ifequal current_page 'fandom_video' %}active2{% endifequal %}"><a href="{% url 'fandom:fandom_video' fandom.id %}">视频</a></li>
                <li class="{% ifequal current_page 'fandom_picture' %}active2{% endifequal %}"><a href="{% url 'fandom:fandom_picture' fandom.id %}">图片</a></li>
                <li class="{% ifequal current_page 'fandom_article' %}active2{% endifequal %}"><a href="{% url 'fandom:fandom_article' fandom.id %}">帖子</a></li>
                <li class="{% ifequal current_page 'fandom_activity' %}active2{% endifequal %}"><a href="{% url 'fandom:fandom_activity' fandom.id %}">活动</a></li>
			</ul>
		</div>
         {% block right_form %}


  {% endblock %}
</section>
<!--sidebar start-->
<section>
    <ul class="sidebar">
        <li class="qq">
            <a target="_blank" href="http://wpa.qq.com/msgrd?v=3&uin=2023525077&site=qq&menu=yes"></a>
        </li>
        <li class="totop"></li>
    </ul>
</section>
{% block totop %}{% endblock %}
</div>


<script>
			(function() {
				var docElem = window.document.documentElement, didScroll, scrollPosition;

				// trick to prevent scrolling when opening/closing button
				function noScrollFn() {
					window.scrollTo( scrollPosition ? scrollPosition.x : 0, scrollPosition ? scrollPosition.y : 0 );
				}

				function noScroll() {
					window.removeEventListener( 'scroll', scrollHandler );
					window.addEventListener( 'scroll', noScrollFn );
				}

				function scrollFn() {
					window.addEventListener( 'scroll', scrollHandler );
				}

				function canScroll() {
					window.removeEventListener( 'scroll', noScrollFn );
					scrollFn();
				}

				function scrollHandler() {
					if( !didScroll ) {
						didScroll = true;
						setTimeout( function() { scrollPage(); }, 60 );
					}
				};

				function scrollPage() {
					scrollPosition = { x : window.pageXOffset || docElem.scrollLeft, y : window.pageYOffset || docElem.scrollTop };
					didScroll = false;
				};

				scrollFn();

				[].slice.call( document.querySelectorAll( '.morph-button' ) ).forEach( function( bttn ) {
					new UIMorphingButton( bttn, {
						closeEl : '.icon-close',
						onBeforeOpen : function() {
							// don't allow to scroll
							noScroll();
						},
						onAfterOpen : function() {
							// can scroll again
							canScroll();
						},
						onBeforeClose : function() {
							// don't allow to scroll
							noScroll();
						},
						onAfterClose : function() {
							// can scroll again
							canScroll();
						}
					} );
				} );

				// for demo purposes only
				[].slice.call( document.querySelectorAll( 'form button' ) ).forEach( function( bttn ) {
					bttn.addEventListener( 'click', function( ev ) { ev.preventDefault(); } );
				} );
			})();
		</script>

</body>
</html>

templates/usercenter-po-article.html
{% extends 'usercenter-base.html' %}
{% block title %}我的发表- 饭友圈在线网{% endblock %}
{% load staticfiles %}
{% block custom_bread %}
<section>
        <div class="wp">
            <ul  class="crumbs">
                <li><a href="{% url 'index' %}">首页</a>></li>
                <li>我的发表</li>
            </ul>
        </div>
    </section>

{% endblock %}
{% block left_content %}
	<div class="left">
        <ul>
            <li ><a href="{% url 'users:user_info' %}">个人资料</a></li>
            <li ><a href="{% url 'users:myfav_fandom' %}">我的圈子</a></li>
            <li ><a href="{% url 'users:myfav_video' %}">我的收藏</a></li>
            <li class="active2"><a href="{% url 'users:mypo_video' %}">我的发表</a></li>
        </ul>
	</div>
{% endblock %}
{% block right_content %}
    <div class="right" >
            <div class="personal_des Releasecont">
                <div class="head">
                    <h1>我的发表</h1>
                </div>
            </div>
            <div class="personal_des permessage">
                <div class="head">
                    <ul class="tab_header messagehead">
                       <li ><a href="{% url 'users:mypo_video' %}">视频</a> </li>
                        <li ><a href="{% url 'users:mypo_picture' %}">图片</a></li>
                        <li class="active"><a href="{% url 'users:mypo_article' %}">帖子</a></li>
                        <li ><a href="{% url 'users:mypo_comment' %}">评论</a></li>
                    </ul>

                </div>
            <div class="messagelist">
                  {% for article in po_article %}
                    <div class="messages butler_list company company-fav-box">
                        <dl class="des fr">
                            <dt>
                                <a href="{% url 'fandom:article_detail' article.id  %}">
                                    <img width="160" height="90" src="/media/{{ article.head_img }}"/>
                                </a>
                            </dt>
                            <dd>
                                <h1><a href="{% url 'fandom:article_detail' article.id  %}">{{ article.title }}</a></h1>
                                <div class="pic fl" style="width:auto;">


                                </div>
                                <span class="c8 clear">{{ article.add_time }}</span>
                                <div class="delete jsDeleteFav_article" data-favid="{{ article.id }}"></div>
                            </dd>
                        </dl>
                    </div>

                    {% endfor %}

                </div>
        </div>
    </div>
    </div>


{% endblock %}

templates/usercenter-po-picture.html
{% extends 'usercenter-base.html' %}
{% block title %}我的发表- 饭友圈在线网{% endblock %}
{% load staticfiles %}
{% block custom_bread %}
<section>
        <div class="wp">
            <ul  class="crumbs">
                <li><a href="{% url 'index' %}">首页</a>></li>
                <li>我的发表</li>
            </ul>
        </div>
    </section>

{% endblock %}
{% block left_content %}
	<div class="left">
        <ul>
            <li ><a href="{% url 'users:user_info' %}">个人资料</a></li>
            <li ><a href="{% url 'users:myfav_fandom' %}">我的圈子</a></li>
            <li ><a href="{% url 'users:myfav_video' %}">我的收藏</a></li>
            <li class="active2"><a href="{% url 'users:mypo_video' %}">我的发表</a></li>
        </ul>
	</div>
{% endblock %}
{% block right_content %}
    <div class="right" >
            <div class="personal_des Releasecont">
                <div class="head">
                    <h1>我的发表</h1>
                </div>
            </div>
            <div class="personal_des permessage">
                <div class="head">
                    <ul class="tab_header messagehead">
                       <li ><a href="{% url 'users:mypo_video' %}">视频</a> </li>
                        <li class="active"><a href="{% url 'users:mypo_picture' %}">图片</a></li>
                        <li ><a href="{% url 'users:mypo_article' %}">帖子</a></li>
                        <li ><a href="{% url 'users:mypo_comment' %}">评论</a></li>
                    </ul>

                </div>
                <div class="companycenter">

                         <div class="group_list brief">
                         {% for po_picture in po_picture %}
                        <div class="module1_5 box">
                            <a href="{% url 'fandom:picture_detail' po_picture.id %}">
                                <img width="214" height="190" src="/media/{{ po_picture.url }}"/>
                            </a>
                            <div class="des">
                                <a href="{% url 'fandom:picture_detail' po_picture.id %}"><h2>{{ po_picture.name }}</h2></a>
                                <span class="fl">所属粉丝圈：<i class="key">{{po_picture.q_name }}</i></span>
                                <span class="fr">点击：{{ po_picture.click_nums }}</span>
                            </div>
                            <div class="bottom">
                                <span class="fl">{{ po_picture.add_time }}</span>
                                <span class="delete-group fr jsDeletePo_picture" data-favid="{{ po_picture.id }}"></span>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
    </div>


{% endblock %}